import { useCallback, useEffect, useMemo, useState } from "react";
import { Building2, Check, ChevronLeft, ChevronRight, Home, LandPlot, Loader2, Plus, Search, Trash2, Upload } from "lucide-react";
import { toast } from "sonner";
import { Link, useOutletContext } from "react-router-dom";
import api, { formatError } from "../../lib/api";
import { formatMoney } from "../../lib/currency";

const SUBTYPES = {
  residential: ["Apartment", "Villa", "Farmhouse", "Independent House", "Plot", "Other"],
  commercial: ["Office", "Shop", "Showroom", "Mall / Retail Space", "Warehouse", "Commercial Building", "Other"],
  land: ["Residential Plot", "Commercial Plot", "Agricultural Land", "Industrial Land", "Other Land"],
  industrial: ["Warehouse", "Factory", "Industrial Plot", "Industrial Shed", "Other"],
  other: ["Custom Property"],
};
const EMPTY = { user_role: "", inventory_source: "", container_kind: "", category: "", subtype: "", structure: "single", name: "", location: "", price: "", status: "available", inventory_owner: "", attributes: {}, inventory_setup: { mode: "manual", towers: 1, floors_per_tower: 1, units_per_floor: 1, total_units: 1 } };
const STEPS = ["Role", "Source", "What", "Category", "Type", "Structure", "Details", "Inventory", "Review"];

export default function Properties() {
  const { ws } = useOutletContext();
  const [properties, setProperties] = useState([]);
  const [form, setForm] = useState(EMPTY);
  const [step, setStep] = useState(0);
  const [open, setOpen] = useState(false);
  const [search, setSearch] = useState("");
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [currency, setCurrency] = useState(ws.currency || "INR");
  const enabled = ws.modules?.real_estate !== false;
  const load = useCallback(async () => {
    if (!enabled) { setLoading(false); return; }
    try { const { data } = await api.get(`/workspaces/${ws.id}/properties`, { params: { search } }); setProperties(data.items || []); setCurrency(data.currency || ws.currency || "INR"); }
    catch (error) { toast.error(formatError(error.response?.data?.detail)); }
    finally { setLoading(false); }
  }, [enabled, search, ws.currency, ws.id]);
  useEffect(() => { load(); }, [load]);
  const set = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  const setAttribute = (key, value) => setForm((current) => ({ ...current, attributes: { ...current.attributes, [key]: value } }));
  const setInventory = (key, value) => setForm((current) => ({ ...current, inventory_setup: { ...current.inventory_setup, [key]: value } }));
  const chooseCategory = (category) => setForm((current) => ({ ...current, category, subtype: SUBTYPES[category][0], attributes: {} }));
  const chooseWhat = (containerKind) => setForm((current) => ({ ...current, container_kind: containerKind, structure: containerKind === "individual" ? "single" : current.structure }));
  const close = () => { setOpen(false); setStep(0); setForm(EMPTY); };
  const totalUnits = useMemo(() => Math.max(1, Number(form.inventory_setup.towers || 1) * Number(form.inventory_setup.floors_per_tower || 1) * Number(form.inventory_setup.units_per_floor || 1)), [form.inventory_setup]);
  const create = async (event) => {
    event.preventDefault(); setSaving(true);
    try { await api.post(`/workspaces/${ws.id}/properties`, { ...form, inventory_setup: { ...form.inventory_setup, total_units: totalUnits } }); toast.success("Property added"); close(); load(); }
    catch (error) { toast.error(formatError(error.response?.data?.detail)); }
    finally { setSaving(false); }
  };
  const remove = async (id) => { try { await api.delete(`/workspaces/${ws.id}/properties/${id}`); setProperties((items) => items.filter((item) => item.id !== id)); } catch (error) { toast.error(formatError(error.response?.data?.detail)); } };
  if (!enabled) return <div className="p-6 sm:p-10 max-w-3xl mx-auto"><div className="rounded-xl border border-dashed bg-card p-10 text-center"><Building2 className="w-10 h-10 mx-auto text-muted-foreground" /><h1 className="mt-4 font-display text-2xl font-black">Properties is not active</h1><p className="mt-2 text-sm text-muted-foreground">Install the Real Estate module in workspace settings to manage property inventory.</p><Link to={`/app/w/${ws.id}/settings`} className="mt-5 inline-flex h-10 items-center rounded-full bg-primary px-4 text-sm font-semibold text-primary-foreground">Open settings</Link></div></div>;
  return <div className="p-6 sm:p-10 max-w-7xl mx-auto space-y-8">
    <header className="flex items-end justify-between gap-4 flex-wrap"><div><div className="inline-flex items-center gap-2 text-xs uppercase tracking-[0.2em] font-bold text-primary"><Building2 className="w-4 h-4" /> Property management</div><h1 className="mt-2 font-display text-3xl font-black tracking-tight">Properties</h1><p className="text-muted-foreground mt-1">Manage real-estate inventory, projects, and units.</p></div><button onClick={() => setOpen(true)} className="inline-flex items-center gap-2 px-4 h-10 rounded-full bg-primary text-primary-foreground text-sm font-semibold"><Plus className="w-4 h-4" /> Add property</button></header>
    <div className="flex items-center gap-2 max-w-xl"><Search className="w-4 h-4 text-muted-foreground" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search properties or locations" className="w-full h-10 px-3 rounded-lg border bg-background text-sm" /></div>
    {loading ? <div className="text-muted-foreground">Loading properties...</div> : properties.length === 0 ? <EmptyState onAdd={() => setOpen(true)} /> : <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{properties.map((property) => <PropertyCard key={property.id} property={property} currency={currency} onDelete={remove} />)}</div>}
    {open && <Wizard form={form} step={step} setStep={setStep} set={set} setAttribute={setAttribute} setInventory={setInventory} chooseCategory={chooseCategory} chooseWhat={chooseWhat} totalUnits={totalUnits} saving={saving} onSubmit={create} onClose={close} />}
  </div>;
}

function Wizard({ form, step, setStep, set, setAttribute, setInventory, chooseCategory, chooseWhat, totalUnits, saving, onSubmit, onClose }) {
  const canContinue = step === 0 ? Boolean(form.user_role) : step === 1 ? Boolean(form.inventory_source) : step === 2 ? Boolean(form.container_kind) : step === 3 ? Boolean(form.category) : step === 4 ? Boolean(form.subtype) : step === 5 ? Boolean(form.structure) : step === 6 ? Boolean(form.name && form.location) : true;
  return <div className="fixed inset-0 z-50 bg-background/80 backdrop-blur-sm p-4 overflow-y-auto"><form onSubmit={onSubmit} className="max-w-3xl mx-auto my-8 rounded-xl border bg-card p-6 sm:p-8 space-y-7">
    <div className="flex items-start justify-between gap-4"><div><div className="text-xs uppercase tracking-[0.2em] font-bold text-primary">Add property</div><h2 className="mt-2 font-display text-2xl font-black">{STEPS[step]}</h2></div><button type="button" onClick={onClose} className="text-sm text-muted-foreground">Close</button></div>
    <div className="flex gap-1 overflow-x-auto pb-1">{STEPS.map((label, index) => <button type="button" key={label} onClick={() => index <= step && setStep(index)} className={`flex items-center gap-1.5 whitespace-nowrap text-xs font-semibold ${index === step ? "text-primary" : index < step ? "text-foreground" : "text-muted-foreground"}`}>{index < step ? <Check className="w-3.5 h-3.5" /> : <span className="grid place-items-center w-5 h-5 rounded-full border">{index + 1}</span>}{label}</button>)}</div>
    {step === 0 && <ChoiceStep title="Who are you?" options={[["developer", "Developer / Builder", "I own or develop properties"], ["channel_partner", "Channel Partner / Broker", "I sell properties for developers or owners"], ["sales_agent", "Sales Agent", "I handle property sales and leads"]]} value={form.user_role} onChange={(value) => set("user_role", value)} />}
    {step === 1 && <ChoiceStep title="Where does this property come from?" options={[["own_inventory", "My Project / Inventory", "Property I own or control"], ["builder_inventory", "Developer / Builder Inventory", "Authorized inventory from a developer"], ["third_party", "Owner / Third Party", "Property listed with permission"], ["existing_inventory", "Assigned / Existing Inventory", "Inventory already assigned to me"]]} value={form.inventory_source} onChange={(value) => set("inventory_source", value)} />}
    {step === 2 && <ChoiceStep title="What are you selling?" options={[["project", "Project / Development", "Multiple properties under one development"], ["individual", "Individual Property", "One villa, office, farmhouse, or other property"], ["land", "Land / Plots", "Land parcel or plotted development"]]} value={form.container_kind} onChange={chooseWhat} />}
    {step === 3 && <ChoiceStep title="What type of property is this?" options={[["residential", "Residential", "Homes and residential developments"], ["commercial", "Commercial", "Offices, shops, and retail"], ["land", "Land", "Plots and agricultural land"], ["industrial", "Industrial", "Warehouses, factories, and sheds"], ["other", "Other", "A custom property type"]]} value={form.category} onChange={chooseCategory} />}
    {step === 4 && <ChoiceStep title="Choose a property subtype" options={(SUBTYPES[form.category] || []).map((item) => [item, item, `Add ${item.toLowerCase()} inventory`])} value={form.subtype} onChange={(value) => set("subtype", value)} />}
    {step === 5 && <StructureStep form={form} set={set} />}
    {step === 6 && <DetailsStep form={form} set={set} setAttribute={setAttribute} />}
    {step === 7 && <InventoryStep form={form} setInventory={setInventory} totalUnits={totalUnits} />}
    {step === 8 && <ReviewStep form={form} totalUnits={totalUnits} />}
    <div className="flex items-center justify-between border-t pt-5"><button type="button" onClick={() => setStep((current) => Math.max(0, current - 1))} disabled={step === 0} className="inline-flex items-center gap-1.5 px-3 h-10 rounded-lg border text-sm font-semibold disabled:opacity-40"><ChevronLeft className="w-4 h-4" /> Back</button>{step < STEPS.length - 1 ? <button type="button" onClick={() => setStep((current) => Math.min(STEPS.length - 1, current + 1))} disabled={!canContinue} className="inline-flex items-center gap-1.5 px-4 h-10 rounded-lg bg-primary text-primary-foreground text-sm font-semibold disabled:opacity-40">Continue <ChevronRight className="w-4 h-4" /></button> : <button disabled={saving} className="inline-flex items-center gap-2 px-5 h-10 rounded-lg bg-primary text-primary-foreground text-sm font-semibold disabled:opacity-50">{saving && <Loader2 className="w-4 h-4 animate-spin" />} Create property</button>}</div>
  </form></div>;
}

function ChoiceStep({ title, options, value, onChange }) { return <section><h3 className="font-display text-xl font-bold mb-4">{title}</h3><div className="grid gap-3 sm:grid-cols-2">{options.map(([key, label, description]) => <button type="button" key={key} onClick={() => onChange(key)} className={`text-left p-4 rounded-xl border transition-colors ${value === key ? "border-primary bg-primary/10" : "hover:bg-accent"}`}><div className="font-semibold">{label}</div><div className="mt-1 text-sm text-muted-foreground">{description}</div></button>)}</div></section>; }
function StructureStep({ form, set }) { const options = form.container_kind === "individual" ? [["single", "Single Property", "One property with no inventory hierarchy"]] : [["single", "Single Property", "One named property or unit"], ["multiple", "Multiple Properties", "A collection of standalone units"], ["tower", "Tower / Block Based", "Towers, floors, and units"], ["plot", "Plot Based", "A development made of plots"]]; return <ChoiceStep title="How is this property structured?" options={options} value={form.structure} onChange={(value) => set("structure", value)} />; }
function DetailsStep({ form, set, setAttribute }) { const land = form.category === "land"; const apartment = form.subtype === "Apartment"; const villa = ["Villa", "Farmhouse", "Independent House"].includes(form.subtype); const commercial = form.category === "commercial"; return <section className="space-y-4"><h3 className="font-display text-xl font-bold">Property details</h3><div className="grid sm:grid-cols-2 gap-3"><Field label={form.container_kind === "project" ? "Project name" : "Property name"} value={form.name} onChange={(value) => set("name", value)} required /><Field label="Location" value={form.location} onChange={(value) => set("location", value)} required /><Field label="Price" value={form.price} onChange={(value) => set("price", value)} /><Field label="Inventory owner" value={form.inventory_owner} onChange={(value) => set("inventory_owner", value)} /></div>{land && <div className="grid sm:grid-cols-2 gap-3"><Field label="Plot / land area" value={form.attributes.landArea || ""} onChange={(value) => setAttribute("landArea", value)} /><Field label="Dimensions" value={form.attributes.dimensions || ""} onChange={(value) => setAttribute("dimensions", value)} /><Field label="Land type" value={form.attributes.landType || ""} onChange={(value) => setAttribute("landType", value)} /></div>}{apartment && <div className="grid sm:grid-cols-2 gap-3"><Field label="BHK" value={form.attributes.bhk || ""} onChange={(value) => setAttribute("bhk", value)} /><Field label="Area" value={form.attributes.area || ""} onChange={(value) => setAttribute("area", value)} /><Field label="Facing" value={form.attributes.facing || ""} onChange={(value) => setAttribute("facing", value)} /></div>}{villa && <div className="grid sm:grid-cols-2 gap-3"><Field label="Bedrooms" value={form.attributes.bedrooms || ""} onChange={(value) => setAttribute("bedrooms", value)} /><Field label="Bathrooms" value={form.attributes.bathrooms || ""} onChange={(value) => setAttribute("bathrooms", value)} /><Field label="Built-up area" value={form.attributes.builtUpArea || ""} onChange={(value) => setAttribute("builtUpArea", value)} /><Field label="Parking" value={form.attributes.parking || ""} onChange={(value) => setAttribute("parking", value)} /></div>}{commercial && <div className="grid sm:grid-cols-2 gap-3"><Field label="Carpet area" value={form.attributes.carpetArea || ""} onChange={(value) => setAttribute("carpetArea", value)} /><Field label="Furnishing" value={form.attributes.furnishing || ""} onChange={(value) => setAttribute("furnishing", value)} /><Field label="Floor" value={form.attributes.floor || ""} onChange={(value) => setAttribute("floor", value)} /></div>}</section>; }
function InventoryStep({ form, setInventory, totalUnits }) { const generated = ["tower", "plot", "multiple"].includes(form.structure); return <section className="space-y-4"><h3 className="font-display text-xl font-bold">Inventory setup</h3><p className="text-sm text-muted-foreground">Choose how Arevei should add the inventory. You can change this later.</p><div className="grid gap-3 sm:grid-cols-3">{[["generate", "Generate automatically", "Create a unit count from your structure"], ["import", "Import CSV / Excel", "Bring an existing inventory"], ["manual", "Add manually", "Start with this property only"]].map(([key, label, description]) => <button type="button" key={key} onClick={() => setInventory("mode", key)} className={`text-left p-4 rounded-xl border ${form.inventory_setup.mode === key ? "border-primary bg-primary/10" : "hover:bg-accent"}`}><div className="flex items-center gap-2 font-semibold">{key === "import" ? <Upload className="w-4 h-4" /> : <Building2 className="w-4 h-4" />}{label}</div><div className="mt-1 text-xs text-muted-foreground">{description}</div></button>)}</div>{form.inventory_setup.mode === "import" && <div className="rounded-lg border border-dashed p-4 text-sm text-muted-foreground">CSV/Excel import can be completed from the property detail view after creation.</div>}{form.inventory_setup.mode === "generate" && generated && <div className="grid sm:grid-cols-3 gap-3"><NumberField label="Towers" value={form.inventory_setup.towers} onChange={(value) => setInventory("towers", value)} /><NumberField label="Floors per tower" value={form.inventory_setup.floors_per_tower} onChange={(value) => setInventory("floors_per_tower", value)} /><NumberField label="Units per floor" value={form.inventory_setup.units_per_floor} onChange={(value) => setInventory("units_per_floor", value)} /></div>}{form.inventory_setup.mode === "generate" && <div className="rounded-xl border bg-primary/5 p-5"><div className="text-sm text-muted-foreground">Inventory preview</div><div className="mt-1 font-display text-3xl font-black">{generated ? totalUnits : 1} <span className="text-base font-medium text-muted-foreground">units</span></div></div>}</section>; }
function ReviewStep({ form, totalUnits }) { return <section className="space-y-4"><h3 className="font-display text-xl font-bold">Review & create</h3><div className="rounded-xl border divide-y">{[["Role", form.user_role], ["Source", form.inventory_source], ["What", form.container_kind], ["Property", `${form.category} · ${form.subtype}`], ["Structure", form.structure], ["Name", form.name], ["Location", form.location], ["Inventory", `${form.inventory_setup.mode} · ${form.inventory_setup.mode === "generate" ? `${totalUnits} units` : "ready"}`]].map(([label, value]) => <div key={label} className="flex justify-between gap-4 p-3 text-sm"><span className="text-muted-foreground">{label}</span><span className="font-semibold capitalize text-right">{String(value || "-").replaceAll("_", " ")}</span></div>)}</div><p className="text-sm text-muted-foreground">You can refine units, availability, and assignments after creating the property.</p></section>; }
function Field({ label, value, onChange, required }) { return <label className="block space-y-1.5"><span className="text-xs font-semibold text-muted-foreground uppercase">{label}</span><input required={required} value={value} onChange={(event) => onChange(event.target.value)} className="w-full h-10 px-3 rounded-lg border bg-background text-sm" /></label>; }
function NumberField({ label, value, onChange }) { return <Field label={label} value={value} onChange={(next) => onChange(Math.max(1, Number(next) || 1))} />; }
function EmptyState({ onAdd }) { return <div className="border border-dashed rounded-xl p-12 text-center bg-card"><Building2 className="w-10 h-10 mx-auto text-muted-foreground" /><h2 className="mt-4 font-display text-xl font-bold">No properties yet</h2><p className="mt-1 text-sm text-muted-foreground">Add a project, individual property, or land parcel to begin.</p><button onClick={onAdd} className="mt-5 inline-flex items-center gap-2 px-4 h-10 rounded-full bg-primary text-primary-foreground text-sm font-semibold"><Plus className="w-4 h-4" /> Add property</button></div>; }
function PropertyCard({ property, currency, onDelete }) { const Icon = property.category === "land" ? LandPlot : property.category === "residential" ? Home : Building2; const numericPrice = Number(String(property.price || "").replaceAll(",", "")); return <article className="rounded-xl border bg-card p-5"><div className="flex items-start justify-between gap-3"><div className="w-10 h-10 rounded-lg bg-primary/10 text-primary grid place-items-center"><Icon className="w-5 h-5" /></div><button onClick={() => onDelete(property.id)} className="text-muted-foreground hover:text-destructive" title="Delete property"><Trash2 className="w-4 h-4" /></button></div><h3 className="mt-4 font-display text-lg font-bold truncate">{property.name}</h3><p className="text-sm text-muted-foreground capitalize">{property.subtype || property.category} · {property.container_kind}</p><p className="mt-3 text-sm text-muted-foreground truncate">{property.location || "Location not set"}</p><p className="mt-3 font-semibold">{Number.isFinite(numericPrice) && property.price !== "" ? formatMoney(numericPrice, currency) : property.price || "Price on request"}</p><div className="mt-4 flex items-center justify-between text-xs"><span className="px-2 py-1 rounded-md border capitalize">{property.status}</span><span className="font-semibold">{property.inventory_setup?.total_units ? `${property.inventory_setup.total_units} units` : "Single inventory"}</span></div></article>; }
