import { useCallback, useEffect, useMemo, useState } from "react";
import { Activity, Bot, Braces, Clock3, Cpu, Loader2, RefreshCw, Sparkles, TriangleAlert, Zap } from "lucide-react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import api, { formatError } from "../lib/api";

const EMPTY = { totals: { input_tokens: 0, output_tokens: 0, total_tokens: 0, calls: 0, failed_calls: 0, metered_calls: 0, average_latency_ms: 0 }, daily: [], processes: [], models: [], recent: [] };
const number = (value) => new Intl.NumberFormat(undefined, { notation: Number(value || 0) >= 10000 ? "compact" : "standard", maximumFractionDigits: 1 }).format(Number(value || 0));
const dateLabel = (value) => new Date(`${value}T00:00:00`).toLocaleDateString(undefined, { month: "short", day: "numeric" });

export default function AIUsageDashboard({ wsId }) {
  const [days, setDays] = useState(30);
  const [data, setData] = useState(EMPTY);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const load = useCallback(async () => {
    setLoading(true); setError("");
    try { const response = await api.get(`/workspaces/${wsId}/ai-usage`, { params: { days } }); setData({ ...EMPTY, ...response.data }); }
    catch (requestError) { setError(formatError(requestError.response?.data?.detail || requestError.message)); }
    finally { setLoading(false); }
  }, [days, wsId]);
  useEffect(() => { load(); }, [load]);
  const maxProcess = Math.max(1, ...data.processes.map((item) => item.total_tokens));
  const meteringRate = data.totals.calls ? Math.round((data.totals.metered_calls / data.totals.calls) * 100) : 100;
  const chart = useMemo(() => data.daily.map((row) => ({ ...row, label: dateLabel(row.day) })), [data.daily]);

  return <section className="relative overflow-hidden rounded-xl border border-primary/20 bg-card p-6 space-y-6">
    <div className="pointer-events-none absolute -right-24 -top-32 h-72 w-72 rounded-full bg-primary/15 blur-3xl" />
    <div className="pointer-events-none absolute -bottom-40 left-1/3 h-72 w-72 rounded-full bg-violet-500/10 blur-3xl" />
    <div className="relative flex flex-wrap items-start justify-between gap-4"><div className="flex items-start gap-3"><div className="grid h-11 w-11 place-items-center rounded-xl border border-primary/30 bg-primary/10 text-primary shadow-[0_0_30px_hsl(var(--primary)/0.18)]"><Sparkles className="h-5 w-5" /></div><div><div className="flex items-center gap-2"><h2 className="font-display text-xl font-bold">AI consumption</h2><span className="rounded-full border border-emerald-500/30 bg-emerald-500/10 px-2 py-0.5 text-[10px] font-bold uppercase text-emerald-500">Live meter</span></div><p className="mt-1 max-w-2xl text-sm text-muted-foreground">Bedrock and connected model usage by workflow. Token records contain counts and operational metadata only; prompts and responses are not stored.</p></div></div><div className="flex items-center gap-2"><select aria-label="Usage period" value={days} onChange={(event) => setDays(Number(event.target.value))} className="h-9 rounded-md border bg-background px-3 text-xs font-semibold"><option value="7">7 days</option><option value="30">30 days</option><option value="90">90 days</option></select><button onClick={load} disabled={loading} className="grid h-9 w-9 place-items-center rounded-md border bg-background hover:bg-accent disabled:opacity-50" title="Refresh usage"><RefreshCw className={`h-4 w-4 ${loading ? "animate-spin" : ""}`} /></button></div></div>
    {error ? <div role="alert" className="relative flex items-center gap-2 rounded-lg border border-destructive/30 bg-destructive/5 p-4 text-sm text-destructive"><TriangleAlert className="h-4 w-4" /> {error}</div> : <>
      <div className="relative grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={Zap} label="Total tokens" value={number(data.totals.total_tokens)} detail={`${number(data.totals.calls)} model calls`} /><Metric icon={Braces} label="Input tokens" value={number(data.totals.input_tokens)} detail="Prompts and context" /><Metric icon={Bot} label="Output tokens" value={number(data.totals.output_tokens)} detail="Generated results" /><Metric icon={Clock3} label="Average latency" value={`${number(data.totals.average_latency_ms)} ms`} detail={`${meteringRate}% calls token-metered`} /></div>
      <div className="relative grid gap-4 xl:grid-cols-[minmax(0,1.5fr)_minmax(300px,1fr)]"><div className="rounded-xl border bg-background/70 p-4"><div className="mb-4 flex items-center justify-between"><div><h3 className="font-semibold">Consumption signal</h3><p className="text-xs text-muted-foreground">Daily input and output tokens</p></div><Activity className="h-4 w-4 text-primary" /></div><div className="h-64">{loading ? <div className="grid h-full place-items-center"><Loader2 className="h-5 w-5 animate-spin text-primary" /></div> : <ResponsiveContainer width="100%" height="100%"><AreaChart data={chart} margin={{ top: 8, right: 8, left: -15, bottom: 0 }}><defs><linearGradient id="inputTokens" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="hsl(var(--primary))" stopOpacity={0.55}/><stop offset="95%" stopColor="hsl(var(--primary))" stopOpacity={0}/></linearGradient><linearGradient id="outputTokens" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#8b5cf6" stopOpacity={0.45}/><stop offset="95%" stopColor="#8b5cf6" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" className="stroke-border" vertical={false} /><XAxis dataKey="label" tick={{ fontSize: 10 }} tickLine={false} axisLine={false} minTickGap={24} /><YAxis tick={{ fontSize: 10 }} tickLine={false} axisLine={false} tickFormatter={number} /><Tooltip formatter={(value, name) => [number(value), name === "input_tokens" ? "Input" : "Output"]} /><Area type="monotone" dataKey="input_tokens" stroke="hsl(var(--primary))" fill="url(#inputTokens)" strokeWidth={2} /><Area type="monotone" dataKey="output_tokens" stroke="#8b5cf6" fill="url(#outputTokens)" strokeWidth={2} /></AreaChart></ResponsiveContainer>}</div></div><div className="rounded-xl border bg-background/70 p-4"><div className="mb-4"><h3 className="font-semibold">Processes consuming AI</h3><p className="text-xs text-muted-foreground">Ranked by total tokens</p></div><div className="space-y-4">{!data.processes.length ? <EmptyUsage /> : data.processes.slice(0, 7).map((item) => <div key={item.key}><div className="mb-1.5 flex items-center justify-between gap-3 text-xs"><span className="truncate font-medium">{item.label}</span><span className="font-mono text-muted-foreground">{number(item.total_tokens)}</span></div><div className="h-1.5 overflow-hidden rounded-full bg-secondary"><div className="h-full rounded-full bg-gradient-to-r from-primary to-violet-500 shadow-[0_0_10px_hsl(var(--primary)/0.4)]" style={{ width: `${Math.max(3, (item.total_tokens / maxProcess) * 100)}%` }} /></div><p className="mt-1 text-[10px] text-muted-foreground">{item.calls} calls · {number(item.input_tokens)} in / {number(item.output_tokens)} out</p></div>)}</div></div></div>
      <div className="relative grid gap-4 lg:grid-cols-2"><Breakdown title="Models and providers" icon={Cpu} empty="Model usage will appear after the next AI action." rows={data.models.map((item) => ({ title: item.model, subtitle: item.provider.replaceAll("_", " "), value: `${number(item.total_tokens)} tokens`, note: `${item.calls} calls` }))} /><Breakdown title="Recent activity" icon={Activity} empty="New AI actions will be recorded here." rows={data.recent.map((item) => ({ title: data.processes.find((process) => process.key === item.process)?.label || item.process?.replaceAll("_", " ") || "AI action", subtitle: `${item.provider?.replaceAll("_", " ")} · ${new Date(item.created_at).toLocaleString()}`, value: `${number(item.total_tokens)} tokens`, note: item.status === "success" ? `${number(item.latency_ms)} ms` : "Failed" }))} /></div>
      {!data.totals.calls && <p className="relative text-center text-xs text-muted-foreground">Metering starts with AI requests made after this update; earlier Bedrock calls do not contain recoverable workspace token records.</p>}
    </>}
  </section>;
}

function Metric({ icon: Icon, label, value, detail }) { return <div className="rounded-xl border bg-background/75 p-4 backdrop-blur"><Icon className="h-4 w-4 text-primary" /><p className="mt-3 font-display text-2xl font-black tracking-tight">{value}</p><p className="text-xs font-semibold">{label}</p><p className="mt-1 text-[10px] text-muted-foreground">{detail}</p></div>; }
function EmptyUsage() { return <div className="grid min-h-36 place-items-center rounded-lg border border-dashed text-center text-xs text-muted-foreground">Run an AI workflow to begin metering.</div>; }
function Breakdown({ title, icon: Icon, empty, rows }) { return <div className="rounded-xl border bg-background/70 p-4"><h3 className="mb-3 flex items-center gap-2 font-semibold"><Icon className="h-4 w-4 text-primary" /> {title}</h3>{!rows.length ? <p className="py-8 text-center text-xs text-muted-foreground">{empty}</p> : <div className="divide-y">{rows.slice(0, 6).map((row, index) => <div key={`${row.title}-${index}`} className="flex items-center justify-between gap-4 py-3"><div className="min-w-0"><p className="truncate text-sm font-medium capitalize">{row.title}</p><p className="truncate text-[10px] text-muted-foreground capitalize">{row.subtitle}</p></div><div className="shrink-0 text-right"><p className="text-xs font-semibold">{row.value}</p><p className="text-[10px] text-muted-foreground">{row.note}</p></div></div>)}</div>}</div>; }
